
const slides = document.querySelectorAll('.slide');
if (slides.length) { let currentSlide = 0; setInterval(() => { slides[currentSlide].classList.remove('active'); currentSlide = (currentSlide + 1) % slides.length; slides[currentSlide].classList.add('active'); }, 4000); }
function filterServices(category, event){ document.querySelectorAll('.filter-btn').forEach(btn=>btn.classList.remove('active')); if(event&&event.target) event.target.classList.add('active'); document.querySelectorAll('.service-card').forEach(card=>{ if(category==='all'||card.classList.contains(category)) card.classList.add('active'); else card.classList.remove('active'); }); }
function openBookingPopup(){ const p=document.getElementById('bookingPopup'); if(p) p.classList.add('active');}
function closeBookingPopup(){ const p=document.getElementById('bookingPopup'); if(p) p.classList.remove('active');}
const popup=document.getElementById('bookingPopup'); if(popup) popup.addEventListener('click', e=>{ if(e.target===popup) closeBookingPopup(); });
setTimeout(()=>{ if(document.getElementById('bookingPopup')) openBookingPopup(); },5000);
const bookingForm=document.getElementById('bookingForm');
if(bookingForm){ bookingForm.addEventListener('submit',function(e){ e.preventDefault(); const name=document.getElementById('customerName').value.trim(); const phone=document.getElementById('customerPhone').value.trim(); const service=document.getElementById('serviceType').value.trim(); const date=document.getElementById('bookingDate').value.trim(); const address=document.getElementById('customerAddress').value.trim(); const message=document.getElementById('customerMessage').value.trim(); if(!name||!phone||!service||!date||!address){ alert('Please fill all required booking details.'); return;} const text=`Hello Tanisk Beauty Zone,%0A%0AI want to book a home salon service in Dehradun.%0A%0AName: ${encodeURIComponent(name)}%0APhone: ${encodeURIComponent(phone)}%0AService: ${encodeURIComponent(service)}%0APreferred Date: ${encodeURIComponent(date)}%0AArea/Address: ${encodeURIComponent(address)}%0AExtra Details: ${encodeURIComponent(message||'N/A')}`; window.open(`https://wa.me/919627189407?text=${text}`,'_blank'); }); }
